version: '3.8'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    volumes:
      - var/run/docker.sock:/var/run/docker.sock  # Для интеграции с Docker
      - traefik.yml:/etc/traefik/traefik.yml     # Конфигурация Traefik
